hystrix:
threadpool:
  default:
    coreSize: 100  # Hystrix Thread Pool default size
    maximumSize: 500  # Hystrix Thread Pool default size
    keepAliveTimeMinutes: 1
    allowMaximumSizeToDivergeFromCoreSize: true
command:
  default:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 3000     #설정 시간동안 처리 지연발생시 timeout and 설정한 fallback 로직 수행
    circuitBreaker:
      requestVolumeThreshold: 2                # 설정수 값만큼 요청이 들어온 경우만 circut open 여부 결정 함
      errorThresholdPercentage: 50        # requestVolumn값을 넘는 요청 중 설정 값이상 비율이 에러인 경우 circuit open
      enabled: true