
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    "HttpBinClient#delay(int)":
      # 최근 1분 내에, 5번 이상의 요청이 있었고, 그 중 50% 이상이 오류가 발생했다면, command를 실행하지 않고 fallback을 실행하겠다는 의미
      execution.isolation.thread.timeoutInMilliseconds: 3000 # hystirx명령에 대해 3초 timeout 설정
      metrics.rollingStats.timeInMilliseconds: 60000 # 60초의 window slice를 가짐(30초씩 감시)
      circuitBreaker.requestVolumeThreshold: 5 # 최소 5번 이상의 요청이 있어야함
      circuitBreaker.errorThresholdPercentage: 50 # 50% 이상 오류가 발생시 회로를 오픈(circuit open)

